spring:
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?useSSL=false&serverTimezone=UTC
    username: root
    password: 20010915tyht

#指明mapper.xml的位置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: dna.springbootweb.model
